version: "3.9"

services:
  api:
    image: ghcr.io/${GITHUB_OWNER}/mirai-api:${TAG:-latest}
    restart: unless-stopped
    env_file: .env.production
    command: uvicorn mirai_api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/healthz"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "128M"
    networks: [mirai]

  trader:
    image: ghcr.io/${GITHUB_OWNER}/mirai-trader:${TAG:-latest}
    restart: unless-stopped
    env_file: .env.production
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'print(0)' >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "768M"
        reservations:
          cpus: "0.10"
          memory: "128M"
    networks: [mirai]

  services:
    image: ghcr.io/${GITHUB_OWNER}/mirai-services:${TAG:-latest}
    restart: unless-stopped
    env_file: .env.production
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "128M"
    networks: [mirai]

networks:
  mirai: {}
