# AlertManager configuration for Mirai Agent
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mirai-agent.com'

# Маршрутизация алертов
route:
  group_by: ['alertname', 'severity', 'component']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'mirai-default'
  routes:
    # Критические алерты - немедленно в Telegram
    - match:
        severity: critical
      receiver: 'mirai-critical'
      group_wait: 5s
      repeat_interval: 15m
    
    # Торговые алерты
    - match:
        component: trading
      receiver: 'mirai-trading'
      group_wait: 30s
      repeat_interval: 2h
    
    # AI алерты
    - match:
        component: ai
      receiver: 'mirai-ai'
      group_wait: 1m
      repeat_interval: 30m
    
    # Системные алерты
    - match:
        component: system
      receiver: 'mirai-system'
      group_wait: 2m
      repeat_interval: 1h

# Получатели уведомлений
receivers:
  - name: 'mirai-default'
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'mirai-critical'
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true
        title: '🚨 КРИТИЧЕСКИЙ АЛЕРТ: {{ .GroupLabels.alertname }}'
        text: |
          🚨 **КРИТИЧЕСКИЙ АЛЕРТ**
          
          **Алерт:** {{ .GroupLabels.alertname }}
          **Статус:** {{ .Status }}
          **Компонент:** {{ .GroupLabels.component }}
          
          {{- range .Alerts }}
          **Описание:** {{ .Annotations.description }}
          **Время:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{- end }}

  - name: 'mirai-trading'
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true
        title: '📈 Торговый алерт: {{ .GroupLabels.alertname }}'
        text: |
          📈 **ТОРГОВЫЙ АЛЕРТ**
          
          **Алерт:** {{ .GroupLabels.alertname }}
          **Статус:** {{ .Status }}
          
          {{- range .Alerts }}
          **Описание:** {{ .Annotations.description }}
          **Время:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{- end }}

  - name: 'mirai-ai'
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true
        title: '🤖 AI алерт: {{ .GroupLabels.alertname }}'
        text: |
          🤖 **AI АЛЕРТ**
          
          **Алерт:** {{ .GroupLabels.alertname }}
          **Статус:** {{ .Status }}
          
          {{- range .Alerts }}
          **Описание:** {{ .Annotations.description }}
          **Время:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{- end }}

  - name: 'mirai-system'
    webhook_configs:
      - url: 'http://localhost:8000/api/alerts/webhook'
        send_resolved: true
        title: '💻 Системный алерт: {{ .GroupLabels.alertname }}'
        text: |
          💻 **СИСТЕМНЫЙ АЛЕРТ**
          
          **Алерт:** {{ .GroupLabels.alertname }}
          **Статус:** {{ .Status }}
          
          {{- range .Alerts }}
          **Описание:** {{ .Annotations.description }}
          **Время:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{- end }}

# Подавление алертов
inhibit_rules:
  # Подавлять предупреждения если есть критические
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']
    
  # Подавлять алерты о системе если AI недоступен
  - source_match:
      alertname: 'AINotResponding'
    target_match:
      component: 'ai'
    equal: ['instance']