# Prometheus configuration for Mirai Agent
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Mirai Agent metrics
  - job_name: 'mirai-agent'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Trading API metrics
  - job_name: 'mirai-trading-api'
    static_configs:
      - targets: ['localhost:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # AI Orchestrator metrics
  - job_name: 'mirai-ai-orchestrator'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Web API metrics
  - job_name: 'mirai-web-api'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # System metrics (node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s

# Remote write configuration (опционально для долгосрочного хранения)
remote_write:
  - url: "http://localhost:9201/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500