groups:
  - name: mirai-trading-alerts
    rules:
    - alert: MiraiAPIDown
      expr: up{job="mirai-api"} == 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Mirai API недоступен"
        
    - alert: HighTradingLoss
      expr: mirai_trading_pnl_total < -1000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Высокие торговые потери: {{ $value }}"
        
    - alert: HighSystemLoad
      expr: node_load1 > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Высокая нагрузка системы: {{ $value }}"
        
    - alert: LowDiskSpace
      expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Мало места на диске: {{ $value }}%"
