# Trading Strategies Configuration

# Global Strategy Settings
global:
  enabled: true
  dry_run: true
  execution_interval: 300  # seconds
  max_concurrent_strategies: 3

# Strategy Definitions
strategies:
  - name: "momentum_breakout"
    description: "Momentum breakout strategy using RSI and volume"
    enabled: true
    symbols: ["BTCUSDT", "ETHUSDT"]
    timeframe: "1h"
    parameters:
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      volume_threshold: 1.5  # Volume multiplier
      breakout_threshold: 0.02  # 2% breakout threshold
    risk:
      max_position_size: 1000.0
      stop_loss_percent: 0.02
      take_profit_percent: 0.04
    
  - name: "mean_reversion"
    description: "Mean reversion strategy using Bollinger Bands"
    enabled: false  # Disabled by default
    symbols: ["ADAUSDT", "DOTUSDT"]
    timeframe: "15m"
    parameters:
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      oversold_threshold: 25
      overbought_threshold: 75
    risk:
      max_position_size: 500.0
      stop_loss_percent: 0.025
      take_profit_percent: 0.035

  - name: "trend_following"
    description: "Trend following strategy using EMA crossover"
    enabled: true
    symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
    timeframe: "4h"
    parameters:
      fast_ema: 12
      slow_ema: 26
      signal_ema: 9
      atr_period: 14
      atr_multiplier: 2.0
    risk:
      max_position_size: 1500.0
      stop_loss_percent: 0.03
      take_profit_percent: 0.06

# Symbol-specific Settings
symbols:
  BTCUSDT:
    min_volume_usdt: 100000000  # Minimum 24h volume in USDT
    max_spread_percent: 0.001   # Maximum bid-ask spread
    trading_hours: "24/7"
    
  ETHUSDT:
    min_volume_usdt: 50000000
    max_spread_percent: 0.001
    trading_hours: "24/7"
    
  ADAUSDT:
    min_volume_usdt: 10000000
    max_spread_percent: 0.002
    trading_hours: "24/7"

# Market Condition Filters
market_filters:
  enabled: true
  
  # Volatility filter
  volatility:
    min_atr_percent: 0.01    # Minimum ATR for trading
    max_atr_percent: 0.10    # Maximum ATR for trading
    
  # Trend filter
  trend:
    use_market_regime: true
    min_trend_strength: 0.3
    
  # Volume filter
  volume:
    min_volume_ratio: 0.8    # Minimum volume vs average
    volume_spike_threshold: 2.0

# Backtesting Configuration
backtesting:
  enabled: false
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 10000.0
  commission: 0.001  # 0.1% commission per trade
  slippage: 0.0005   # 0.05% slippage

# Alerts and Notifications
alerts:
  enabled: true
  discord_webhook: ""  # Discord webhook URL for alerts
  telegram_bot_token: ""
  telegram_chat_id: ""
  
  # Alert triggers
  triggers:
    - "trade_executed"
    - "stop_loss_hit"
    - "take_profit_hit"
    - "high_drawdown"
    - "system_error"