name: Build All Images
on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event.inputs.push_images == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: app/api
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ghcr.io/ageekey/mirai-api:${{ github.event.inputs.push_images == 'true' && 'latest' || 'test' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Trader  
        uses: docker/build-push-action@v6
        with:
          context: app/trader
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ghcr.io/ageekey/mirai-trader:${{ github.event.inputs.push_images == 'true' && 'latest' || 'test' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Services
        uses: docker/build-push-action@v6
        with:
          context: web/services
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ghcr.io/ageekey/mirai-services:${{ github.event.inputs.push_images == 'true' && 'latest' || 'test' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


