name: Build All Images
on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase owner
        id: vars
        run: echo "owner_lc=${ACTOR,,}" >> $GITHUB_OUTPUT
        env:
          ACTOR: ${{ github.actor }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-api
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-trader  
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-services
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: app/api
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-api:latest
            ${{ startsWith(github.ref, 'refs/tags/v') && format('ghcr.io/{0}/mirai-api:{1}', steps.vars.outputs.owner_lc, github.ref_name) || '' }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build & Push Trader
        uses: docker/build-push-action@v6
        with:
          context: app/trader
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-trader:latest
            ${{ startsWith(github.ref, 'refs/tags/v') && format('ghcr.io/{0}/mirai-trader:{1}', steps.vars.outputs.owner_lc, github.ref_name) || '' }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build & Push Services
        uses: docker/build-push-action@v6
        with:
          context: web/services
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-services:latest
            ${{ startsWith(github.ref, 'refs/tags/v') && format('ghcr.io/{0}/mirai-services:{1}', steps.vars.outputs.owner_lc, github.ref_name) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
