name: CI API
on:
  push: { paths: ["app/api/**"] }
  pull_request: { paths: ["app/api/**"] }

permissions:
  contents: read
  packages: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
          cache: 'pip'
      - run: pip install -U pip setuptools wheel
        timeout-minutes: 5
      - run: |
          cd app/api
          pip install --timeout 300 --retries 3 -e .[dev]
        timeout-minutes: 10
      - run: ruff check app/api --output-format=github
      - run: |
          cd app/api
          PYTHONPATH=. mypy -p mirai_api
      - run: |
          cd app/api
          pytest -v tests/

      - name: Compute lowercase owner
        id: vars
        run: echo "owner_lc=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: app/api
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max