name: CI API
on:
  push: { paths: ["app/api/**"] }
  pull_request: { paths: ["app/api/**"] }
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -U pip
      - run: pip install -e app/api[dev]
      - run: ruff check app/api
      - run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/app/api" >> $GITHUB_ENV
      - run: mypy -p mirai_api
      - run: pytest -q app/api/tests
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: app/api
          push: false