name: CI Services
on:
  push: { paths: ["web/services/**"] }
  pull_request: { paths: ["web/services/**"] }

permissions:
  contents: read
  packages: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'web/services/package-lock.json'
      - run: cd web/services && npm cache clean --force && npm ci
        timeout-minutes: 10
      - run: cd web/services && npm run lint
      - run: cd web/services && npm run test
        if: false  # Temporarily disable tests until they're implemented
      - run: cd web/services && npm run build

      - name: Compute lowercase owner
        id: vars
        run: echo "owner_lc=${ACTOR,,}" >> $GITHUB_OUTPUT
        env:
          ACTOR: ${{ github.actor }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.owner_lc }}/mirai-services
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: web/services
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max