name: Release & Build Images

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: api
            context: app/api
            image: mirai-api
          - name: trader
            context: app/trader
            image: mirai-trader
          - name: services
            context: web/services
            image: mirai-services
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          body: |
            ## 🚀 Mirai Agent Release ${{ steps.version.outputs.version }}
            
            ### Docker Images
            - `ghcr.io/${{ github.repository_owner }}/mirai-api:${{ steps.version.outputs.version }}`
            - `ghcr.io/${{ github.repository_owner }}/mirai-trader:${{ steps.version.outputs.version }}`
            - `ghcr.io/${{ github.repository_owner }}/mirai-services:${{ steps.version.outputs.version }}`
            
            ### Latest Images
            - `ghcr.io/${{ github.repository_owner }}/mirai-api:latest`
            - `ghcr.io/${{ github.repository_owner }}/mirai-trader:latest`
            - `ghcr.io/${{ github.repository_owner }}/mirai-services:latest`
