name: Test GHCR Push

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push test image (API)
        uses: docker/build-push-action@v6
        with:
          context: app/api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mirai-api:test
          platforms: linux/amd64
